---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-web-view
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-web-view
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: [list, get]
- nonResourceURLs:
  - '*'
  verbs: [list, get]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-web-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-web-view
subjects:
- kind: ServiceAccount
  name: kube-web-view
  namespace: default
