apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-web-view
  name: kube-web-view
spec:
  selector:
    application: kube-web-view
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
